### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by samanthavbarron** [coddingtonbear/obsidian-local-rest-api#106]
Is there any interest in having this in a docker image? I would use it, and I suspect others might as well. If this sounds like a welcome contribution, I could take a stab at it.

**Comment by samanthavbarron** [comment]
Closing this as I've misunderstood what this does. I thought this was headless. Oops!

**Comment by kylek29** [comment]
For what it's worth, you can still create a Docker of it as long as you have LiveSync (paid or the free open source version) enabled. This allows you to point your devices with the Chrome WebClipper to the Docker.

I was configuring one a few days ago but didn't finish it, it uses a Docker with a lite-weight GUI, the Obsidian LiveSync plugin, and the Local REST API plugin so that Obsidian can run in it.
