### ISSUE TITLE
POST /active/ append method always create extra paragraph

### ISSUE THREAD

**Issue by Luiz-nyan** [coddingtonbear/obsidian-local-rest-api#120]
The `POST /active/` method is creating a extra paragraph before the data. For example, when i try to send a frontmatter like "---/ntags: /n---", the plugin render this:

---
tags: 
---

**Comment by coddingtonbear** [comment]
I'm afraid that's not a bug, but understand that it might be inconvenient for your usecase.  The `POST` method is intended to be used for appending to an existing file, and we *do* ensure that your existing file ends in a newline so as to prevent folks from needing to first `GET` a file and then `POST` to it to make sure that a newline exists at the end of whatever content you're appending to.

Luckily, though, in your case, there's an easier option: if you're trying to write frontmatter via your request, then, as you know, that frontmatter must be the absolute first item in the document: so you should just use `PUT` (replace file contents) instead of `POST` (append to existing file contents) so as to avoid this behavior.

Good luck!
