### ISSUE TITLE
[Bug] Failed to upgrade/install on the obsidian community plugin page

### ISSUE THREAD

**Issue by kaiiiz** [coddingtonbear/obsidian-local-rest-api#25]
Thanks for the bug fixes in the latest release. However, the plugin install page can't work anymore. I'm not sure what problem it is since the developer console only shows 404 not found.

<img width="1900" alt="image" src="https://user-images.githubusercontent.com/30596812/170864203-e8f14dfb-b7d9-4875-9240-42c418167ce0.png">

I suspect that there are two possible reasons:

1. The release branch name should be **master** instead of **main** according to the [Official Release Guides](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+plugin+to+the+community+plugin+list). It seems that the setting of [community-plugin repo](https://github.com/obsidianmd/obsidian-releases/blob/master/community-plugins.json#L3373-L3379) doesn't specify `branch` property, so it uses the default branch setting (`master`). However, Github may redirect the master branch to the main branch, so I'm not sure whether this is the root cause.
2. The release name inconsistency. As mentioned in [the latest release](https://github.com/coddingtonbear/obsidian-local-rest-api/releases/tag/1.3.8), there is no release version 1.3.7 in the Github repo, but the community plugin page shows that the latest version of the plugin is 1.3.7.

**Comment by coddingtonbear** [comment]
Oh, no, the branch name doesn't matter, actually -- I've been using `main` since the beginning of the project without trouble.  What _is_ wrong is that I didn't quite perform the release steps correctly because I was in a bit of a rush and the release steps for this particular project are a little weird compared to my others.

I've just a moment ago kicked-off a new build & am fairly sure that'll fix things up.

**Comment by coddingtonbear** [comment]
Just a moment ago found a minute to verify that this particular build did succeed & is installable; I think we're ok now!
