### ISSUE TITLE
[Feature] Support momentJS or time template while using Obsidian web

### ISSUE THREAD

**Issue by Quorafind** [coddingtonbear/obsidian-local-rest-api#3]
Please consider adding a feature like {{time: HH:mm}}.

**Comment by coddingtonbear** [comment]
Hey there @Quorafind -- that's not a bad idea.  I think you intend to post this to obsidian-web: https://github.com/coddingtonbear/obsidian-web since the templating is handled there instead of here.

Do try to post as a discussion (see the "Discussions" tab at the top of the screen here: https://github.com/coddingtonbear/obsidian-web) , though, rather than as an issue.  Once you start a discussion there, we can talk over what the obstacles for that might be (there is at least one!).

Cheers!
