### ISSUE TITLE
Cannot create folders

### ISSUE THREAD

**Issue by juangamnik** [coddingtonbear/obsidian-local-rest-api#56]
I tried to create a new folder and cannot find a corresponding "command", and the "vault files" resource explicitly denies (with status code 405) to create a folder (e.g. via PUT). So how can I create a new folder in a vault with the REST API?

**Comment by juangamnik** [comment]
I looked through the open pull request and saw #44, which is related to #43. The solution there is to auto create folders. That would be a solution to my problem either as I try to create notes in a folder that das not exist in the vault, yet.

**Comment by coddingtonbear** [comment]
For sure -- this is a documented behavior, unfortunately; so this doesn't qualify as a bug.  Maybe you can help @SettingDust work through #44, though, to solve your use case?

**Comment by juangamnik** [comment]
Why do you close this? It is a feature of obsidian not supported via the rest api…

**Comment by juangamnik** [comment]
So in essence: Why is creating a folder not part of the rest api

**Comment by coddingtonbear** [comment]
I'm closing this because this is not a bug, it's just not a feature even if you imagine it should be one. The mechanisms this plugin uses for interacting with your Obsidian vault do not interact with your vault as if it's a raw filesystem -- they instead interact with your vault via APIs Obsidian provides and that imposes certain quirks (see #21 for example).

If you'd like to shepherd through a solution on this, you are absolutely welcome to either contribute a solution to this via #44, invent and PR your own solution out of whole cloth, or are welcome to start a discussion to see if you can find somebody to write a solution for you (you can use the "Ideas" section for that sort of thing).

In any case: I'm afraid "Issues" on this project are for actual bugs or planned work, not feature requests.

**Comment by juangamnik** [comment]
@coddingtonbear: I am curious (I did not write any Plugins for Obsidian, yet) in the [API Spec](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts) in line [3762ff](https://github.com/obsidianmd/obsidian-api/blob/583ba39e3f6c0546de5e5e8742256a60e2d78ebc/obsidian.d.ts#L3762) there is a public class method (for class `Vault`) called `createFolder(path: string): Promise<void>` defined. Does it not work or why do you think it is documented behavior that folders cannot be created (not necessarily automatically but with a dedicated REST call)?

**Comment by coddingtonbear** [comment]
I think the answer to your question is on #44 -- have a look there and you'll see what the hang-up is.  As I mentioned earlier, you can absolutely feel free to help work through the problems on that PR if you'd like to have this as a new feature of the REST API this plugin provides.

**Comment by juangamnik** [comment]
Sorry I read the comments on #44, but do not find any hint regarding a "hang-up". For me that PR is not necessarily the solution. For me it would be already helpful, if the Obsidian API function `Vault.createFolder()` would be exposed via the REST API. If I find some time I'll take a look at the implementation, but as I said I am not familiar with your Plugin or the Obsidian Plugin API.
